In [ ]:
!python3 run_filter_test.py 1

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 1
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7783.  7397.  4758. 10917.  1054.    91.]
[+] Validation:
 [1861. 1873. 1271. 2707.  269.   19.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [2]:
!python3 run_filter_test.py 2

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 2
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7742.  7423.  4822. 10878.  1045.    90.]
[+] Validation:
 [1902. 1847. 1207. 2746.  278.   20.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [3]:
!python3 run_filter_test.py 3

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 3
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7712.  7381.  4853. 10910.  1064.    80.]
[+] Validation:
 [1932. 1889. 1176. 2714.  259.   30.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [4]:
!python3 run_filter_test.py 4

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 4
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7673.  7407.  4854. 10935.  1038.    93.]
[+] Validation:
 [1971. 1863. 1175. 2689.  285.   17.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [5]:
!python3 run_filter_test.py 5

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 5
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7739.  7454.  4841. 10841.  1031.    94.]
[+] Validation:
 [1905. 1816. 1188. 2783.  292.   16.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [6]:
!python3 run_filter_test.py 6

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 6
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7714.  7386.  4877. 10902.  1040.    81.]
[+] Validation:
 [1930. 1884. 1152. 2722.  283.   29.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [7]:
!python3 run_filter_test.py 7

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 7
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7677.  7474.  4827. 10888.  1042.    92.]
[+] Validation:
 [1967. 1796. 1202. 2736.  281.   18.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [8]:
!python3 run_filter_test.py 8

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 8
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7673.  7346.  4871. 10948.  1071.    91.]
[+] Validation:
 [1971. 1924. 1158. 2676.  252.   19.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [9]:
!python3 run_filter_test.py 9

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 9
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7732.  7385.  4785. 10945.  1064.    89.]
[+] Validation:
 [1912. 1885. 1244. 2679.  259.   21.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape       

In [10]:
!python3 run_filter_test.py 10

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 10
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7689.  7439.  4778. 10939.  1071.    84.]
[+] Validation:
 [1955. 1831. 1251. 2685.  252.   26.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape      

In [11]:
!python3 run_filter_test.py 11

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 11
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7735.  7379.  4809. 10923.  1065.    89.]
[+] Validation:
 [1909. 1891. 1220. 2701.  258.   21.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape      

In [12]:
!python3 run_filter_test.py 12

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[!] Now performing test: 12
[i] Loaded Parameters:
 40000 35 0.2 200 
 dataset/glove/glove.twitter.27B.200d.txt
[i] . Reading from csv file...Done!
[i] Found 30505 unique tokens.
[+] Shape of data tensor: (40000, 30)
[+] Shape of label tensor: (40000, 6)
[+] Number of entries in each category:
[+] Training:
 [ 7708.  7427.  4788. 10944.  1045.    88.]
[+] Validation:
 [1936. 1843. 1241. 2680.  278.   22.]
[i] Loading GloVe from: dataset/glove/glove.twitter.27B.200d.txt ...Done.
[+] Proceeding with Embedding Matrix...Completed!
Finished running setup.
_________________________________________________________________
Layer (type)                 Output Shape      